from sys import argv
script, filename = argv
print(f'we are going to delete the content of {filename}')
print(f'if you are willing to do it press enter, if not then press ctrl + d')
input('?')
print(f'opening the file now')
target = open(filename, 'w')
#print(f'truncating the file now ... goodbye.')
#target.truncate()
print(f'give three lines of input now')
line1 = input('line 1:')
line2 = input('line 2:')
line3 = input('line 3:')
print(f'i am going to write these to file now')
target.write(line1)
target.write("\n")
target.write(line2)
target.write("\n")
target.write(line3)
print(f'closing the file now')
target.close()
target = open(filename,'r')
out = target.read()
print(out)
for i in range(2):
    print('this is {} -> \n'.format(i) + out)